### ISSUE TITLE
Feature request: cocoapod

### ISSUE THREAD

**Issue by ConfusedVorlon** [Ideon/SmudgeKit#2]
very nice kit - thanks for sharing.

would be great to get a cocoapod for this...

thanks.

**Comment by hpeikemo** [comment]
Thanks! Don't use much cocoapods myself, but it would be a useful experience to add that. 
You got any example files? A pull request would be even better ;)

**Comment by ConfusedVorlon** [comment]
wow - you're missing some real joy if you're not using them!

re examples: http://cocoapods.org/ (click on creating a pod)
there are loads of examples at the default podspec repo:
https://github.com/CocoaPods/Specs/tree/master/Specs

it should be as simple as this one:
https://github.com/CocoaPods/Specs/blob/master/Specs/PureLayout/2.0.2/PureLayout.podspec.json

**Comment by hpeikemo** [comment]
Cocoapod up and running thanks to @phatblat

**Comment by ConfusedVorlon** [comment]
nice - thank you!
