### ISSUE TITLE
Update code sample

### ISSUE THREAD

**Issue by Davidkle** [Ideon/SmudgeKit#3]
It's better to check if the window is SmudgyWindow instead of checking for the existence of a window.
- (UIWindow *)window
  {
  if ([_window isKindOfClass:[SmudgyWindow class]] == NO)
  {
      _window = [[SmudgyWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  }
  return _window;
  }

**Comment by hpeikemo** [comment]
Why? It seems ill-advised to replace an already instantiated window.
(Keep in mind I'm totally ignorant about xibs and storyboards.)

**Comment by hpeikemo** [comment]
Closing this for now, feel free to reopen this if I've missed something.
