### ISSUE TITLE
Stops appearing after modal presentation

### ISSUE THREAD

**Issue by cwagdev** [Ideon/SmudgeKit#9]
I am not sure if I just did something wrong, but anytime I present a new view controller modally the indicator stops appearing. If I stay within my `UINavigationController` stack all is well. 

Thoughts?

**Comment by hpeikemo** [comment]
Interesting. Must be a bug. Will need to investigate. 
Have you tried using the the latest revision? @rolleric introduced some improvements in abf4a50d9efbc2f00354619bb846d7446649942e that might help for that specific issue

**Comment by cwagdev** [comment]
Yep! That commit does fix the issue. Thanks.

**Comment by hpeikemo** [comment]
Sweet!
